import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import {useEffect} from 'react'
import { Box } from '@mui/material'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  useEffect(() => {
    createMap();
  }, []);

  function createMap() {
    mapboxgl.accessToken = process.env.NEXT_PUBLIC_MAP_BOX_KEY;

    const map = new mapboxgl.Map({
        container: 'map', // container ID
        style: 'mapbox://styles/mapbox/streets-v12', // style URL
        center: [-74.5, 40], // starting position [lng, lat]
        zoom: 1 // starting zoom
    });

    map.on('load', () => {
      map.addLayer({
          id: 'terrain-data',
          type: 'line',
          source: {
              type: 'vector',
              url: 'mapbox://mapbox.mapbox-terrain-v2'
          },
          'source-layer': 'contour'
      });
  });
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Box id='map' sx={{
          width:1,
          height: "100vh"
        }}></Box>
      </main>
    </>
  )
}
